# Generated by `rjournal_article()` using `knitr::purl()`: do not edit by hand
# Please edit matrixExercise.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = F, eval = F)

library(tidyverse)
library(magrittr)
library(extrafont)

sampleFromDist <- function(D, n = 1) {
  
  if (!all(names(D) == c("distribution", "parameters"))) stop("Incorrect distribution object.")
  
  if (tolower(D$distribution) == "gamma") {
    rgamma(n, shape = D$parameters[1], rate = D$parameters[2])
  }
  else if (tolower(D$distribution) == "beta") {
    rbeta(n, shape1 = D$parameters[1], shape2 = D$parameters[2])
  }
  else {
    stop(paste0("Unknown distribution:", D$distribution))
  }
}


## ---- echo = T----------------------------------------------------------------
Fecundity <- list(distribution = "Gamma", parameters = c(47.4, 8.66))
SexRatio <- list(distribution = "Beta", parameters = c(31.2, 29.2))
SurvivalFemale <- list(distribution = "Beta", parameters = c(2.89, 1.46))
SurvivalJuveniles <- list(distribution = "Beta", parameters = c(1.92, 1.54))
SurvivalMale <- list(distribution = "Beta", parameters = c(2.82, 1.55))


## ---- echo = T----------------------------------------------------------------
CarryingCapacity <- 100 * 37 # = 3700


## ---- echo = T----------------------------------------------------------------
constructMatrix <- function(Pop, Fec, SR, Sj, Sf, Sm, K, h) {
  ## Pop: Population structure after removal
  ## Fec: Fecundity
  ## SR : Sex Ratio
  ## Sj : Survival juveniles
  ## Sf : Survival female
  ## Sm : survival male
  ## K  : Carrying capacity
  ## h  ; hunting pressure
  
  # Initialize Leslie matrix with zeros
  TM <- matrix(0, nrow = 3, ncol = 3)
  # Juveniles born
  TM[1, 2] <- Sf * Fec * exp(-sum(Pop)/K)
  # Juveniles maturing to females
  TM[2, 1] <- Sj * SR
  # Juveniles maturing to males
  TM[3, 1] <- Sj * (1 - SR)
  # Adult female surval
  TM[2, 2] <- Sf
  # Adult male survival
  TM[3, 3] <- Sm
  
  # Subtract hunting pressure if supplied
  TM - if (!missing(h)) matrix(rep(h, 3), ncol = 3) else 0
}

sampleParam <- function(Pop = c(50, 70, 30), K = CarryingCapacity, h = c(0, 0, 0)) {
  list(Fec = sampleFromDist(Fecundity),
       SR  = sampleFromDist(SexRatio),
       Sf  = sampleFromDist(SurvivalFemale),
       Sm  = sampleFromDist(SurvivalMale),
       Sj  = 0.364,
       Pop = Pop,
       K   = K,
       h   = h)
}


## ---- echo = F----------------------------------------------------------------
library(furrr)
library(colorspace)
library(metR)
library(geomtextpath)
library(geom)

calcLambda <- function(param) {
  do.call(constructMatrix, param) %>% 
    eigen() %$%
    values %>% 
    first %>% 
    Re
}

plan("multisession", workers = 8)
juvenileFemaleHunting <- tibble(
  f = seq(0, 0.2, length.out = 25),
  j = seq(0, 0.5, length.out = 25)
) %>% 
  complete(f, j) %>% 
  slice(rep(1:n(), 200)) %>% 
  mutate(
    lambda = future_map2_dbl(f,j, function(hF, hJ) {
      sampleParam(h = c(hJ, hF, 0)) %>% 
        calcLambda
    })
  )
plan("sequential")

tValueStat <- function(x) {
  mod          <- lm(x ~ 1)
  coefficients <- summary(mod)$coefficients[1, ]
  
  t.value      <- coefficients[3] %>% 
    unname %>% 
    unclass
  
  t.value
}

juvenileFemaleHuntingPlt <- juvenileFemaleHunting %>%
  group_by(cut_width(f, 0.015, boundary = 0), cut_width(j, 0.04, boundary = 0)) %>%
  summarize(across(!lambda, min),
            lambda = mean(lambda),
            .groups = "drop") %>%
  ggplot(aes(j, f, z = lambda)) +
  geom_contour_fill(breaks = seq(-2, 2, .1),
                    aes(fill = after_stat(level_high),
                        color = after_scale(fill))) +
  geom_contour2(aes(label = after_stat(format(level, nsmall = 1))),
                skip = 0,
                label.placer = isoband::label_placer_manual(
                  # This is just done because I for my OCD's sake;
                  # I think it looks better when the contour labels are aligned
                  breaks = rev(seq(.5, 1.1, .1)), # label values (i.e. what number should be displayed)
                  x = c(rep(.075,5), 0.69, 0.85), # label x-coordinate (panel coordinates NOT data)
                  y = c(0.086, 0.25, 0.38, 0.54, 0.8, 0.753, 0.753),  # label y-coordinate (panel coordinates NOT data)
                  theta = rep(0, 7) # label text angle (0 = no rotation)
                ),
                family = "CMU Serif",
                fontface = "bold",
                margin = margin(2,2,2,2, "mm")) +
  colorspace::scale_fill_continuous_diverging(palette = "Blue-Red 2", 
                                              mid = 1,
                                              rev = T,
                                              breaks = seq(0.4, 1.2, .1)) +
  scale_x_continuous(labels = scales::label_percent()) +
  scale_y_continuous(labels = scales::label_percent()) +
  coord_equal(expand = F) +
  guides(fill = guide_colorbar(
    ticks.colour = "black",
    ticks.linewidth = .25,
    frame.colour = "black",
    frame.linewidth = .5,
  )) +
  ggpubr::theme_pubr(legend = "right", base_family = "CMU Serif") +
  labs(x = "Juvenile Hunting Pressure", 
       y = "Female Hunting Pressure", 
       fill = latex2exp::TeX("Population\nGrowth Rate ($\\lambda$)")) + 
  theme(title = element_text(face = "bold",
                             size = 14),
        axis.title.x = element_text(margin = margin(6,0,0,0,"mm")),
        axis.title.y = element_text(margin = margin(0,4,0,0,"mm")),
        legend.text = element_text(size = 12),
        legend.title = element_text(margin = margin(0,0,0,-11,"mm"), # This margin is added to allow centering of the wide legend title
                                    size = 18),
        aspect.ratio = 1,
        legend.box.margin = margin(0, 0, -5.7, 12, "mm"),            # \|/ Likewise
        legend.key.height = unit(16, "mm"),
        legend.key.width = unit(15, "mm"),
        legend.box.spacing = unit(1, "mm"))

ggsave("juvenileFemaleHuntingPressure.pdf", juvenileFemaleHuntingPlt,
       device = cairo_pdf, width = 4, height = 3, scale = 2)


## ---- echo = F----------------------------------------------------------------
mlPheno <- sapply(1:10000, function(x) 
  c(Fec = sampleFromDist(Fecundity),
    SR  = sampleFromDist(SexRatio),
    Sf  = sampleFromDist(SurvivalFemale),
    Sm  = sampleFromDist(SurvivalMale),
    Sj  = sampleFromDist(SurvivalJuveniles)
  )) %>% 
  t %>% 
  colMeans()

A     <- do.call(constructMatrix, c(as.list(mlPheno), list(Pop = c(30, 70, 50), K = CarryingCapacity))) 
sigma <- c(0.72, 0.08, 0.12)
init  <- c(30, 70, 50)

nextGen <- function(prev, A, sigma, r = 0) {
  exp(rnorm(3, log(as.vector(A %*% (prev - r))), sigma))
}

simNGen <- function(n, init, K, P, ...) {
  history <- matrix(c(init, rep(NA, (n - 1) * length(init))), n, length(init), T)
  
  for (i in 2:n) {
    prev        <- history[i - 1, ]
    A           <- do.call(constructMatrix, c(as.list(P), list(Pop = prev, K = K))) 
    history[i,] <- nextGen(prev, A, ...)
  }
  
  history
}

simNGen(100, init, CarryingCapacity, mlPheno, sigma, r = c(5, 30, 10)) %>% 
  rowSums %>% 
  plot(type = "l")

