---
title: "Exercise"
author: "Vildsvinegruppen"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = F)

library(tidyverse)
library(magrittr)
library(extrafont)

sampleFromDist <- function(D, n = 1) {
  
  if (!all(names(D) == c("distribution", "parameters"))) stop("Incorrect distribution object.")
  
  if (tolower(D$distribution) == "gamma") {
    rgamma(n, shape = D$parameters[1], rate = D$parameters[2])
  }
  else if (tolower(D$distribution) == "beta") {
    rbeta(n, shape1 = D$parameters[1], shape2 = D$parameters[2])
  }
  else {
    stop(paste0("Unknown distribution:", D$distribution))
  }
}

```

# Question

How large is the maximal sustainable hunting pressure on wild boars in Tofte Skov?


# Phenology Parameters

From article (REF):

```{r, echo = T}
Fecundity <- list(distribution = "Gamma", parameters = c(47.4, 8.66))
SexRatio <- list(distribution = "Beta", parameters = c(31.2, 29.2))
SurvivalFemale <- list(distribution = "Beta", parameters = c(2.89, 1.46))
SurvivalJuveniles <- list(distribution = "Beta", parameters = c(1.92, 1.54))
SurvivalMale <- list(distribution = "Beta", parameters = c(2.82, 1.55))
```

# Population Transition Matrix

Formulas from article (REF):

```{r, echo = T}
constructMatrix <- function(Pop, Fec, SR, Sj, Sf, Sm, K, h) {
  ## Pop: Population structure after removal
  ## Fec: Fecundity
  ## SR : Sex Ratio
  ## Sj : Survival juveniles
  ## Sf : Survival female
  ## Sm : survival male
  ## K  : Carrying capacity
  
  TM <- matrix(0, nrow = 3, ncol = 3)
  
  # Juveniles born
  TM[1, 2] <- Sf * Fec * exp(-sum(Pop)/K)
  
  # Juveniles maturing to females
  TM[2, 1] <- Sj * SR
  
  # Juveniles maturing to males
  TM[3, 1] <- Sj * (1 - SR)
  
  # Adult female surval
  TM[2, 2] <- Sf
  
  # Adult male survival
  TM[3, 3] <- Sm
  
  if (!missing(h)) {
    TM - matrix(rep(h, 3), ncol = 3)
  } 
  else {
    TM
  }
}
```


# Simulation loop

```{r, echo = T}
results <- lapply(rep(seq(10, 100, 5), each = 100), function(R) {
  phenologyParameters <- list(
    Fec = Fecundity %>% 
      sampleFromDist,
    SR = SexRatio %>% 
      sampleFromDist,
    Sf = SurvivalFemale %>% 
      sampleFromDist,
    Sm = SurvivalMale %>% 
      sampleFromDist,
    Sj = 0.364#SurvivalJuveniles %>% 
    #sampleFromDist,
    ,
    K = 4*800,
    Pop = c(50, 70, 30)
  )
  
  populationHistory <- matrix(ncol = 3, nrow = 0)
  
  
  for (i in seq(100)) {
    
    phenologyParameters$Pop <- phenologyParameters$Pop -
      as.vector(table(factor(sample.int(3, R, T), levels = c("1", "2", "3"))))
    
    PopMatrix <- do.call(constructMatrix, phenologyParameters)
    
    phenologyParameters$Pop <- as.vector(PopMatrix %*% phenologyParameters$Pop) 
    
    phenologyParameters$Pop[phenologyParameters$Pop < 0] <- 0
    
    
    populationHistory <- rbind(populationHistory, phenologyParameters$Pop)
    
  }
  
  populationHistory %>% 
    set_colnames(c("Juveniles", "Females", "Males")) %>% 
    as_tibble() %>% 
    mutate(
      Generation = row_number(),
      HuntingPressure = R
    )
}) %>% 
  bind_rows()  
```


```{r}
# results %>% 
#   pivot_longer(c(Juveniles, Females, Males), names_to = "Stage", values_to = "Individuals") %>% 
#   ggplot(aes(Generation, Individuals, color = Stage, group = paste0(Stage, Simulation))) +
#   geom_line(alpha = 0.1,
#             key_glyph = draw_key_point) +
#   stat_summary_bin(aes(group = Stage),
#                    binwidth = 5,
#                    fun.data = median_hilow) +
#   guides(color = guide_legend(override.aes = list(alpha = 1,
#                                                   size = 2,
#                                                   shape = 16))) +
#   facet_wrap(~Stage, ncol = 1) +
#   ggpubr::theme_pubr() +
#   theme(aspect.ratio = 0.5)


# results %>% 
#   mutate(PopulationSize = Juveniles + Females + Males) %>% 
#   # filter(Generation > 50) %>%
#   ggplot(aes(HuntingPressure, PopulationSize, z = Generation)) +
#   stat_summary_2d(binwidth = c(5, 50)) +
#   # scale_color_viridis_c() +
#   # geom_hex(aes(color = after_scale(fill))) +
#   scale_fill_viridis_c(option = "A") +
#   coord_cartesian(expand = F) +
#   ggpubr::theme_pubr(legend = "right") +
#   theme(aspect.ratio = 1)
```

# Result

```{r, fig.width=8, fig.height=6}
stochasticHuntingPressure <- results %>% 
  mutate(PopulationSize = Juveniles + Females + Males) %>%
  filter(Generation == 100) %>% 
  mutate(Survived = as.numeric(PopulationSize != 0)) %>% 
  ggplot(aes(HuntingPressure, Survived)) +
  geom_bin2d(binwidth = c(5, 0.05)) +
  geom_smooth(method = "glm",
              method.args = list(family = "binomial")) +
  scale_fill_viridis_c(option = "A", direction = -1,
                       guide = "none") +
  scale_y_continuous(labels = scales::label_percent()) +
  ggpubr::theme_pubr(legend = "right",
                     base_family = "CMU Serif") +
  coord_cartesian(expand = F) +
  labs(x = "Hunting Pressure (Individuals)", y = "Probability of the population\nnot crashing within 100 generations") +
  theme(
    title = element_text(face = "plain",
                         size = 16),
    axis.title.x = element_text(
      margin = margin(1, unit = "lines")
    )
  )

ggsave("stochasticHuntingPressure.png", stochasticHuntingPressure,
       device = cairo_pdf,
       width = 4, height = 3, scale = 2.5)
```



```{r}
sampleParam <- function(Pop = c(50, 70, 30), K = 4*800, h = c(0, 0, 0)) {
  list(
    Fec = Fecundity %>% 
      sampleFromDist,
    SR = SexRatio %>% 
      sampleFromDist,
    Sf = SurvivalFemale %>% 
      sampleFromDist,
    Sm = SurvivalMale %>% 
      sampleFromDist,
    Sj = 0.364#SurvivalJuveniles %>% 
    #sampleFromDist,
    ,
    Pop = Pop,
    K = K,
    h = h
  )
}

calcLambda <- function(param) {
  do.call(constructMatrix, param) %>% 
    eigen() %$%
    values %>% 
    first %>% 
    Re
}

growthRateHuntingPressure_DF <- tibble(h = rep(seq(0, 1, 0.005), each = 3)) %>%
  mutate(stage = rep(c("J", "F", "M"), 1 + 1/0.005) %>% 
           factor(levels = c("J", "F", "M"))) %>% 
  mutate(
    lambda = map2(h, stage, function(x, y) {
      
      hS <- c(0,0,0)
      if (y == "J") hS[1] <- x
      if (y == "F") hS[2] <- x
      if (y == "M") hS[3] <- x
      
      sapply(1:100, function(DUMMY) sampleParam(h = hS) %>% 
               calcLambda())
    }) 
  )

AnalyticGrowthRate <- growthRateHuntingPressure_DF %>% 
  unnest(lambda) %>%
  ggplot(aes(h, lambda, fill = stage)) +
  # geom_smooth() +
  stat_summary_bin(aes(color = after_scale(fill)),
                   fun.data = ~tibble(ymin = quantile(., 0.25), y = median(.), ymax = quantile(., 0.75)),
                   geom = "line",
                   linewidth = 1,
                   binwidth = 0.01) +
  stat_summary_bin(aes(color = after_scale(fill)),
                   fun.data = ~tibble(ymin = quantile(., 0.25), y = median(.), ymax = quantile(., 0.75)),
                   geom = "ribbon",
                   alpha = 0.5,
                   linewidth = 0.75,
                   binwidth = 0.01) +
  geom_hline(yintercept = 1, color = "firebrick", linewidth = 1.25) +
  scale_fill_brewer(palette = "Dark2",
                    labels = ~sapply(., function(x) switch(x, "J" = "Juvenile", "F" = "Female", "M" = "Male"))) +
  scale_x_continuous(labels = scales::label_percent()) +
  ggpubr::theme_pubr(base_family = "CMU Serif", legend = "right") +
  labs(x = "% Individuals culled per generation", y = latex2exp::TeX("Growth rate $(\\lambda)$"), fill = "Lifestage") +
  coord_cartesian(xlim = c(0, 1), expand = F) +
  theme(title = element_text(face = "plain",
                             size = 16),
        axis.title.x = element_text(
          margin = margin(1, unit = "lines")
        ),
        legend.position = c(0.2, 0.3),
        legend.background = element_rect(color = "gray35",
                                         linewidth = .75)
  )


ggsave("AnalyticGrowthRate.pdf", AnalyticGrowthRate,
     device = cairo_pdf,
     width = 4, height = 3, scale = 2)
```
